// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/metrics-actions/ContrastPanel.tsx": () => import("../components/mockups/metrics-actions/ContrastPanel.tsx"),
  "./components/mockups/metrics-actions/ControlRoom.tsx": () => import("../components/mockups/metrics-actions/ControlRoom.tsx"),
  "./components/mockups/metrics-actions/DecisionDeck.tsx": () => import("../components/mockups/metrics-actions/DecisionDeck.tsx"),
  "./components/mockups/metrics-actions/SignalFlow.tsx": () => import("../components/mockups/metrics-actions/SignalFlow.tsx")
};
